### ISSUE TITLE
requestKyc takes 3 args

### ISSUE THREAD

**Issue by brukeg** [Sila-Money/Sila-Python#2]
Sample.md reads like so:

```
payload={

        "user_handle": "user.silamoney.eth"    #Required
    }

User.requestKyc(silaApp,payload)
```

But I think it should included `User.requestKyc(silaApp,payload,user_private_key)` which is just like /checkKyc. I wasn't able to get it to work without the private key, and the error I kept on getting was prompting me for a third argument, the users private key.

**Comment by deepanshutyagi** [comment]
yeah it needs a private key, will edit that

**Comment by brukeg** [comment]
Looks like you did it bro :+1:
