### ISSUE TITLE
Getting error: No module named 'cytoolz.itertoolz'

### ISSUE THREAD

**Issue by storecash** [Sila-Money/Sila-Python#24]
We installed sila python SDK using PIP & trying to use in a function. 
**pip3 install silasdk==0.2.21**
Getting below error.
Unable to import module: No module named 'cytoolz.itertoolz'
Version: Python 3.8

Is there any fix for the sdk ?
_```
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from silasdk import App
  File "/home/runner/test-1/silasdk/__init__.py", line 1, in <module>
    from .ethwallet import EthWallet
  File "/home/runner/test-1/silasdk/ethwallet.py", line 1, in <module>
    from eth_account import Account
  File "/home/runner/test-1/eth_account/__init__.py", line 1, in <module>
    from eth_account.account import (  # noqa: F401
  File "/home/runner/test-1/eth_account/account.py", line 8, in <module>
    from cytoolz import (
  File "/home/runner/test-1/cytoolz/__init__.py", line 1, in <module>
    from .itertoolz import *
ModuleNotFoundError: No module named 'cytoolz.itertoolz'
```_

**Comment by brukeg** [comment]
@storecash Thanks for the heads up. Our SDK team will take a look momentarily. Please stand by

**Comment by brukeg** [comment]
@storecash https://pyinstaller.readthedocs.io/en/stable/feature-notes.html#cython-support. 

> if you are using a Cython C object module, which imports Python modules, you will have to list these as --hidden-import.

**Comment by storecash** [comment]
Hello,
We are not using anything other than the pip3 install silasdk==0.2.21 in a folder.

so is the SILA SDK not taking care of dependencies ?

**Comment by ElFitaFlores** [comment]
If you're using a M1 Mac there is some arch problems with the cytoolz library. I solved it reinstalling python from the x86 version of brew (you can find the guide [here](https://medium.com/mkdir-awesome/how-to-install-x86-64-homebrew-packages-on-apple-m1-macbook-54ba295230f) ), then recreating the virtual env usgin this new python and lastly doing the pip install again.

**Comment by Spikesdev** [comment]
> .itertoolz

have you find any fix for your problem?
